// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/string_command.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "github.com/duosonic62/go-strings-history/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStringCommandRepository is a mock of StringCommandRepository interface
type MockStringCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStringCommandRepositoryMockRecorder
}

// MockStringCommandRepositoryMockRecorder is the mock recorder for MockStringCommandRepository
type MockStringCommandRepositoryMockRecorder struct {
	mock *MockStringCommandRepository
}

// NewMockStringCommandRepository creates a new mock instance
func NewMockStringCommandRepository(ctrl *gomock.Controller) *MockStringCommandRepository {
	mock := &MockStringCommandRepository{ctrl: ctrl}
	mock.recorder = &MockStringCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStringCommandRepository) EXPECT() *MockStringCommandRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockStringCommandRepository) Save(guitarString *entity.GuitarString) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", guitarString)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockStringCommandRepositoryMockRecorder) Save(guitarString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStringCommandRepository)(nil).Save), guitarString)
}

// Update mocks base method
func (m *MockStringCommandRepository) Update(guitarString *entity.GuitarString) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", guitarString)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockStringCommandRepositoryMockRecorder) Update(guitarString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStringCommandRepository)(nil).Update), guitarString)
}

// FindByID mocks base method
func (m *MockStringCommandRepository) FindByID(iD string) (*entity.GuitarString, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", iD)
	ret0, _ := ret[0].(*entity.GuitarString)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockStringCommandRepositoryMockRecorder) FindByID(iD interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStringCommandRepository)(nil).FindByID), iD)
}
