// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/factory/token.go

// Package mock_factory is a generated GoMock package.
package mock_factory

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTokenFactory is a mock of TokenFactory interface
type MockTokenFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTokenFactoryMockRecorder
}

// MockTokenFactoryMockRecorder is the mock recorder for MockTokenFactory
type MockTokenFactoryMockRecorder struct {
	mock *MockTokenFactory
}

// NewMockTokenFactory creates a new mock instance
func NewMockTokenFactory(ctrl *gomock.Controller) *MockTokenFactory {
	mock := &MockTokenFactory{ctrl: ctrl}
	mock.recorder = &MockTokenFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTokenFactory) EXPECT() *MockTokenFactoryMockRecorder {
	return m.recorder
}

// Gen mocks base method
func (m *MockTokenFactory) Gen() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gen")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gen indicates an expected call of Gen
func (mr *MockTokenFactoryMockRecorder) Gen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gen", reflect.TypeOf((*MockTokenFactory)(nil).Gen))
}
