// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/outputboundary/user_command.go

// Package mock_outputboundary is a generated GoMock package.
package mock_outputboundary

import (
	input "github.com/duosonic62/go-strings-history/pkg/usecase/input"
	output "github.com/duosonic62/go-strings-history/pkg/usecase/output"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserCommandPresenter is a mock of UserCommandPresenter interface
type MockUserCommandPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandPresenterMockRecorder
}

// MockUserCommandPresenterMockRecorder is the mock recorder for MockUserCommandPresenter
type MockUserCommandPresenterMockRecorder struct {
	mock *MockUserCommandPresenter
}

// NewMockUserCommandPresenter creates a new mock instance
func NewMockUserCommandPresenter(ctrl *gomock.Controller) *MockUserCommandPresenter {
	mock := &MockUserCommandPresenter{ctrl: ctrl}
	mock.recorder = &MockUserCommandPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserCommandPresenter) EXPECT() *MockUserCommandPresenterMockRecorder {
	return m.recorder
}

// OutputAddUser mocks base method
func (m *MockUserCommandPresenter) OutputAddUser(output output.UserAddOutputData, ctx input.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputAddUser", output, ctx)
}

// OutputAddUser indicates an expected call of OutputAddUser
func (mr *MockUserCommandPresenterMockRecorder) OutputAddUser(output, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputAddUser", reflect.TypeOf((*MockUserCommandPresenter)(nil).OutputAddUser), output, ctx)
}

// OutputEditUser mocks base method
func (m *MockUserCommandPresenter) OutputEditUser(output output.UserEditOutputData, ctx input.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputEditUser", output, ctx)
}

// OutputEditUser indicates an expected call of OutputEditUser
func (mr *MockUserCommandPresenterMockRecorder) OutputEditUser(output, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputEditUser", reflect.TypeOf((*MockUserCommandPresenter)(nil).OutputEditUser), output, ctx)
}

// OutputDeleteUser mocks base method
func (m *MockUserCommandPresenter) OutputDeleteUser(ctx input.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OutputDeleteUser", ctx)
}

// OutputDeleteUser indicates an expected call of OutputDeleteUser
func (mr *MockUserCommandPresenterMockRecorder) OutputDeleteUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputDeleteUser", reflect.TypeOf((*MockUserCommandPresenter)(nil).OutputDeleteUser), ctx)
}
