// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Guitar            string
	GuitarString      string
	Member            string
	StringExchangeLog string
}{
	Guitar:            "guitar",
	GuitarString:      "guitar_string",
	Member:            "member",
	StringExchangeLog: "string_exchange_log",
}
